-- =====================================================================
-- HQ Marketplace — Phase 2 / Notifications
-- 014_user_notifications.sql
-- In-app notifications for users, generated by the database itself when
-- an order's status changes.
--
-- Everything here is additive. No existing column is retyped, no existing
-- policy is widened, and no data is rewritten, so a rollback of this file
-- leaves the schema exactly as 013 left it.
--
-- Why a trigger and not application code:
--   the order status is changed by two different paths (staff PATCH and
--   customer self-cancel), and a third will arrive with payments. A
--   trigger makes "a status change creates a notification" a property of
--   the table, not a habit of every writer that has to remember it.
--
-- Why per-user rows and not a broadcast:
--   a notification the customer has not read yet is the customer's
--   private state, and RLS is the project's answer to private state.
--   Per-user rows also make unread counts and the mark-read endpoint
--   trivial, and allow per-user dismissal without touching anyone else.
-- =====================================================================

CREATE TABLE IF NOT EXISTS user_notifications (
    notification_id  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id          BIGINT      NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    -- 'order' today; the type keeps email/push dispatch and the frontend
    -- icon set from needing a schema change when more kinds arrive.
    notification_type TEXT       NOT NULL,
    -- The thing the notification is about. Typed jsonb so a future
    -- 'review_replied' notification does not force an order_id column.
    payload           JSONB     NOT NULL,
    -- Set when the notification was generated by a status change; null
    -- for notifications the platform sends directly (announcements).
    related_order_id  BIGINT,
    is_read           BOOLEAN    NOT NULL DEFAULT FALSE,
    read_at           TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT user_notifications_type_len CHECK (char_length(notification_type) BETWEEN 1 AND 40),
    CONSTRAINT user_notifications_order_type
        CHECK ((notification_type = 'order_status' AND related_order_id IS NOT NULL)
            OR (notification_type <> 'order_status'))
);

CREATE INDEX ix_user_notifications_user ON user_notifications (user_id, is_read, created_at DESC);
CREATE INDEX ix_user_notifications_order ON user_notifications (related_order_id);

COMMENT ON TABLE user_notifications IS
    'In-app notifications, one row per recipient. Generated by the '
    'order_status_notification trigger for status changes, and insertable '
    'directly by the platform for announcements.';

-- ---------------------------------------------------------------------
-- Isolation: the JWT-derived user id is the only identity allowed to
-- read or change its own notifications.
-- ---------------------------------------------------------------------
ALTER TABLE user_notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_notifications_owner_access ON user_notifications;
CREATE POLICY user_notifications_owner_access ON user_notifications
    FOR ALL
    USING (user_id = app_user_id())
    WITH CHECK (user_id = app_user_id());

-- ---------------------------------------------------------------------
-- The trigger: a status change on an order writes a notification to the
-- customer, inside the writer's own transaction.
-- ---------------------------------------------------------------------
-- Security of execution: the trigger runs with the privileges of the
-- invoking role (hq_app). RLS on user_notifications would normally stop
-- hq_app from inserting a row for another user, so the policy above is
-- the only lever, and it allows exactly what the platform means: the
-- current user's own rows. The insert below targets the *customer's*
-- user_id, which is not the caller's id, so the policy would reject it.
--
-- The clean solution, kept inside the project's non-owner-role rule:
-- SECURITY DEFINER on the trigger function, owned by the table owner,
-- restricted to INSERT ... user_notifications and nothing else. The
-- table owner is not the API role, and the API still cannot write
-- anyone's rows except through this one audited path.
CREATE OR REPLACE FUNCTION notify_order_status_change() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.order_status = OLD.order_status THEN
        RETURN NEW;
    END IF;

    INSERT INTO user_notifications (user_id, notification_type, payload, related_order_id)
    VALUES (
        NEW.customer_id,
        'order_status',
        jsonb_build_object(
            'orderNumber', NEW.order_number,
            'fromStatus',  OLD.order_status,
            'toStatus',    NEW.order_status,
            'businessId',  NEW.business_id
        ),
        NEW.order_id
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION notify_order_status_change() IS
    'Creates the customer notification when an order status changes. '
    'SECURITY DEFINER so the trigger can write the customer''s row even '
    'though hq_app cannot write another user''s notifications directly.';

DROP TRIGGER IF EXISTS trg_orders_status_notify ON orders;
CREATE TRIGGER trg_orders_status_notify
    AFTER UPDATE OF order_status ON orders
    FOR EACH ROW EXECUTE FUNCTION notify_order_status_change();
